imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:

  dependencies:
    before:
      - "mkdir -p /home/scrutinizer/build/cache/anax"
      - "mkdir -p /home/scrutinizer/build/build/coverage.clover"

  tests:
    environment:
      php:
        version: 7.3

    before:
      - "chmod -R 777 /home/scrutinizer/build/cache/anax"
      - "chmod -R 777 /home/scrutinizer/build/build/coverage.clover"

    override:
      -
        command: "make phpunit"
